In [0]:
import json
import scipy as sp
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # plotting stuff
from pprint import pprint
from google.colab import drive

In [0]:
drive.mount('/content/drive')

In [0]:
PATH = "content/drive/My Drive/Colab Notebooks/data/YugiohCardDB/"

In [0]:
with open("drive/My Drive/Colab Notebooks/data/YugiohCardDB/cardinfo.php.json") as f:
    data = json.load(f)

In [0]:
f"{PATH}cardinfo.php.json"

'content/drive/My Drive/Colab Notebooks/data/YugiohCardDB/cardinfo.php.json'

In [0]:
!ls

drive  sample_data


In [0]:
data[0][9:13]

[{'archetype': None,
  'atk': '1400',
  'attribute': 'EARTH',
  'ban_goat': None,
  'ban_ocg': None,
  'ban_tcg': None,
  'def': '300',
  'desc': 'Twice per turn, you can send 1 face-up Continuous Spell or Continuous Trap Card you control to the Graveyard to inflict 500 damage to your opponent.',
  'id': '114932',
  'image_url': 'https://ygoprodeck.com/pics/114932.jpg',
  'image_url_small': 'https://ygoprodeck.com/pics_small/114932.jpg',
  'level': '3',
  'linkmarkers': None,
  'linkval': None,
  'name': 'Seismic Crasher',
  'race': 'Rock',
  'scale': None,
  'set_tag': 'FOTB-EN027,',
  'setcode': 'Force of the Breaker,',
  'type': 'Effect Monster'},
 {'archetype': 'Laval',
  'atk': '2100',
  'attribute': 'FIRE',
  'ban_goat': None,
  'ban_ocg': None,
  'ban_tcg': None,
  'def': '200',
  'desc': 'You can Normal Summon this card without Tributing. If you do, during the End Phase: Send it to the Graveyard. When this card on the field is destroyed and sent to the Graveyard: You can target

In [0]:
transitionMatrix = [[0.2,0.6,0.2],[0.1,0.6,0.3],[0.2,0.7,0.1]]
transitionMatrix

[[0.2, 0.6, 0.2], [0.1, 0.6, 0.3], [0.2, 0.7, 0.1]]

In [0]:
transitionMatrix[1][0]

0.1

In [0]:
dict = {'Name': 'Zara', 'Age': 7}
dict['Name']

KeyError: ignored

In [0]:
def squrOut(m):
  ms = m.shape[0]
  mv = np.vstack( [ m , np.zeros(ms) ] )
  return np.column_stack( [ mv , np.zeros(ms+1) ] )

In [0]:
def addToChain(w,v,t,m):
  if not(w in t):
    t.append(w)
    m = squrOut(m)
  b = t.index(w)
  m[b][v] = m[b][v]+1
  return [b,t,m]

In [0]:
nbeud['desc']

'"Blue-Eyes White Dragon" + "Blue-Eyes White Dragon" + "Blue-Eyes White Dragon"\nAt the end of the Damage Step, if this is the only face-up card you control, and this Fusion Summoned card attacked: You can send 1 "Blue-Eyes" Fusion Monster from your Extra Deck to the Graveyard; this card can attack again in a row. You can use this effect of "Neo Blue-Eyes Ultimate Dragon" up to twice per turn. During either player\'s turn, when a card or effect is activated that targets a "Blue-Eyes" monster(s) you control: You can banish this card from your Graveyard; negate the activation, and if you do, destroy that card.'

In [0]:
text=['[blank]']
mat=np.zeros((1,1))
word=''
quoted=False
reserved='.,;:'
slashed=False
lastword=0
for l in nbeud['desc']: 
  if quoted:
    if l=='"':
      quoted=False
    else: 
      word=word+l
  elif slashed:
    slashed=False
  else:
    if l==' ':
      [lastword,text,mat]=addToChain(word,lastword,text,mat)
      word=''
    elif l in reserved:
      [lastword,text,mat]=addToChain(word,lastword,text,mat)
      word=l
    elif l=='"':
      word=''
      quoted=True
    elif l=='\\':
      [lastword,text,mat]=addToChain(word,lastword,text,mat)
      word=''
      slashed=True
    else: 
      word=word+l
text.append(word)

In [0]:
print(text)
print(mat)

['[blank]', 'Blue-Eyes White Dragon', '+', 'Blue-Eyes White Dragon\nAt', 'the', 'end', 'of', 'Damage', 'Step', ',', 'if', 'this', 'is', 'only', 'face-up', 'card', 'you', 'control', 'and', 'Fusion', 'Summoned', 'attacked', ':', 'You', 'can', 'send', '1', 'Blue-Eyes', 'Monster', 'from', 'your', 'Extra', 'Deck', 'to', 'Graveyard', ';', 'attack', 'again', 'in', 'a', 'row', '.', 'use', 'effect', 'Neo Blue-Eyes Ultimate Dragon', 'up', 'twice', 'per', 'turn', 'During', 'either', "player's", 'when', 'or', 'activated', 'that', 'targets', 'monster(s)', 'banish', 'negate', 'activation', 'do', 'destroy', '.']
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 2. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
nbeud={};
for i in data[0]:
  if i['id'] == '56532353':
    nbeud=i
nbeud['desc']

'"Blue-Eyes White Dragon" + "Blue-Eyes White Dragon" + "Blue-Eyes White Dragon"\nAt the end of the Damage Step, if this is the only face-up card you control, and this Fusion Summoned card attacked: You can send 1 "Blue-Eyes" Fusion Monster from your Extra Deck to the Graveyard; this card can attack again in a row. You can use this effect of "Neo Blue-Eyes Ultimate Dragon" up to twice per turn. During either player\'s turn, when a card or effect is activated that targets a "Blue-Eyes" monster(s) you control: You can banish this card from your Graveyard; negate the activation, and if you do, destroy that card.'

In [0]:
nbeud['desc']

'"Blue-Eyes White Dragon" + "Blue-Eyes White Dragon" + "Blue-Eyes White Dragon"\nAt the end of the Damage Step, if this is the only face-up card you control, and this Fusion Summoned card attacked: You can send 1 "Blue-Eyes" Fusion Monster from your Extra Deck to the Graveyard; this card can attack again in a row. You can use this effect of "Neo Blue-Eyes Ultimate Dragon" up to twice per turn. During either player\'s turn, when a card or effect is activated that targets a "Blue-Eyes" monster(s) you control: You can banish this card from your Graveyard; negate the activation, and if you do, destroy that card.'

In [0]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def myfunc(self):
    print("Hello my name is " + self.name)

In [0]:
def addToMat():
  print("Hello my name is " + self.name)

In [0]:
p1 = Person("John", 36)
p1.myfunc()       

Hello my name is John


In [0]:
mat=[[]]
mat.append(['1'])
mat[0].append('2')
mat[1].append('3')
mat[0].insert(4,'4')
mat[0].insert(1,'5')

In [0]:
mat

[['2', '5', '4'], ['1', '3']]

In [0]:
p = np.zeros((0,0))

array([], shape=(0, 0), dtype=float64)

In [0]:
def squrOut(m):
  ms = m.shape[0]
  mv = np.vstack( [ m , np.zeros(ms) ] )
  return np.column_stack( [ mv , np.zeros(ms+1) ] )

In [0]:
p = np.zeros((2,2))

In [0]:
p = np.zeros((4,4))
p.shape

(4, 4)

In [0]:
p=squrOut(p)

In [0]:
p.shape

(5, 5)